# fly --target spring login --concourse-url https://ci.spring.io --team-name "spring-team"
# fly --target spring set-pipeline --config pipeline.yml --load-vars-from=credentials.yml --pipeline reactor-tools
# fly --target spring trigger-job --job=reactor-tools/build -w
---
resource_types:
- name: artifactory-resource
  type: docker-image
  source:
    repository: springio/artifactory-resource
    tag: 0.0.6

resources:
- name: source
  type: git
  source:
    uri: https://github.com/reactor/reactor-tools.git
    branch: master

- name: tagged-source
  type: git
  source:
    uri: https://github.com/reactor/reactor-tools.git
    branch: master
    tag_filter: "*"

- name: artifactory-repo
  type: artifactory-resource
  source:
    uri: "https://repo.spring.io"
    username: {{artifactory-username}}
    password: {{artifactory-password}}
    build_name: reactor-tools

jobs:
- name: build
  serial: true
  plan:
  - get: source
    trigger: true

  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: openjdk, tag: 8-jdk }
      inputs:
      - name: source
      outputs:
      - name: distribution-repository
      caches:
        - path: source/.gradle
      run:
        dir: source
        path: bash
        args:
        - -exc
        - |
          rm -rf ~/.gradle
          ln -s $PWD/.gradle ~/.gradle
          ./gradlew build publish -Pversion=1.0.0.BUILD-SNAPSHOT
          cp -a build/repo/. ../distribution-repository/
          find ../distribution-repository

  - put: artifactory-repo
    params:
      repo: libs-snapshot-local
      folder: distribution-repository
      build_uri: "https://ci.spring.io/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
      build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
      disable_checksum_uploads: true

- name: release-milestone
  serial: true
  plan:
  - get: tagged-source
    trigger: true

  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: openjdk, tag: 8-jdk }
      inputs:
      - name: tagged-source
      outputs:
      - name: distribution-repository
      caches:
        - path: tagged-source/.gradle
      run:
        dir: tagged-source
        path: bash
        args:
        - -exc
        - |
          TAG=$(git tag --points-at HEAD)

          rm -rf ~/.gradle
          ln -s $PWD/.gradle ~/.gradle
          ./gradlew build publish -Pversion=$TAG
          cp -a build/repo/. ../distribution-repository/
          find ../distribution-repository

  - put: artifactory-repo
    params:
      repo: libs-milestone-local
      folder: distribution-repository
      build_uri: "https://ci.spring.io/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
      build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
      disable_checksum_uploads: true
